apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    component: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: api-port
